reviewers:
  # The default reviewers
  defaults:
    - repository-owners # GitHub team

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # GitHub team

options:
  ignore_draft: true
