reviewers:
  # The default reviewers
  defaults:
    - carcamoa # username
    - karzunn
    - carcamog

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - carcamoa # username
    - karzunn
    - carcamog

options:
  ignore_draft: true
