reviewers:
  # The default reviewers
  defaults:
    - birds

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    groups:
      birds:
        - carcamoa # username
        - karzunn
        - carcamog

options:
  ignore_draft: true
  enable_group_assignment: true